### ISSUE TITLE
XML-Only Page button leads to Home page.

### ISSUE THREAD

**Issue by gmarintes** [marklogic-community/data-explorer#127] opened 2018-04-30 05:17 UTC

**Comment by markschiffner** [comment] 2018-04-30 13:51
@nlaprell Can you take a look at this, investigate.  I know that you fixed this in #14.  Did this somehow creep back in?  Is it merge issue? Is it a different data set?

**Comment by nlaprell** [comment] 2018-05-11 21:44
It looks like this issue was originally fixed by @vjsaradhi (My name was on it for migrating it from JIRA). Possible a roll issue? I'm unable to reproduce it on my environment at this time.

**Comment by nlaprell** [comment] 2018-06-15 16:36
Closing this issue as it was likely resolved in #95 that addressed permissions issues that caused the user to be bounced out to the home page.

**Closed by nlaprell** 2018-06-15 16:36 UTC
Labels: Component - UI, Priority - High
